In [6]:
import pandas as pd

In [7]:
# Load dataset paths
data_folder = "ml-100k/"
u_data_path = data_folder + "u.data"
u_item_path = data_folder + "u.item"
u_genre_path = data_folder + "u.genre"

In [8]:
# Load ratings
df_ratings = pd.read_csv(u_data_path, sep="\t", names=["user_id", "movie_id", "rating", "timestamp"], usecols=[1, 2])

In [9]:
# Load genres
df_genres = pd.read_csv(u_genre_path, sep="|", names=["genre", "genre_id"], index_col="genre_id")

In [10]:
# Load movies with genres
df_movies = pd.read_csv(u_item_path, sep="|", names=["movie_id", "title", "release_date", "empty", "imdb_url"] + list(df_genres["genre"]), encoding="latin-1")
df_movies = df_movies.drop(columns=["empty", "imdb_url"])

In [11]:
# Calculate popularity
df_popularity = df_ratings.groupby("movie_id").size().reset_index(name="num_ratings")
df_movies = df_movies.merge(df_popularity, on="movie_id", how="left").fillna(0)

In [12]:
# Extract top 5 movies per genre
top_movies = {}
for genre in df_genres["genre"]:
    if genre != "unknown":
        genre_movies = df_movies[df_movies[genre] == 1]
        top_movies[genre] = genre_movies.nlargest(5, "num_ratings")[["title", "num_ratings"]]

In [13]:
# Display top movies per genre
for genre, movies in top_movies.items():
    print(f"Top 5 movies for genre: {genre}")
    print(movies, "\n")

Top 5 movies for genre: Action
                              title  num_ratings
49                 Star Wars (1977)          583
180       Return of the Jedi (1983)          507
299            Air Force One (1997)          431
120   Independence Day (ID4) (1996)          429
173  Raiders of the Lost Ark (1981)          420

Top 5 movies for genre: Adventure
                               title  num_ratings
49                  Star Wars (1977)          583
180        Return of the Jedi (1983)          507
173   Raiders of the Lost Ark (1981)          420
116                 Rock, The (1996)          378
171  Empire Strikes Back, The (1980)          367

Top 5 movies for genre: Animation
                           title  num_ratings
0               Toy Story (1995)          452
70         Lion King, The (1994)          220
94                Aladdin (1992)          219
587  Beauty and the Beast (1991)          202
431              Fantasia (1940)          174

Top 5 movies for genre: Children's
                                            title  num_ratings
0                                Toy Story (1995)          452
150  Willy Wonka and the Chocolate Factory (1971)          326
422             E.T. the Extra-Terrestrial (1982)          300
131                      Wizard of Oz, The (1939)          246
70                          Lion King, The (1994)          220

Top 5 movies for genre: Comedy
                                            title  num_ratings
293                              Liar Liar (1997)          485
0                                Toy Story (1995)          452
203                     Back to the Future (1985)          350
150  Willy Wonka and the Chocolate Factory (1971)          326
172                    Princess Bride, The (1987)          324

Top 5 movies for genre: Crime
                          title  num_ratings
99                 Fargo (1996)          508
126       Godfather, The (1972)          413
55          Pulp Fiction (1994)          394
301    L.A. Confidential (1997)          297
11   Usual Suspects, The (1995)          267

Top 5 movies for genre: Documentary
                             title  num_ratings
47              Hoop Dreams (1994)          117
31                    Crumb (1994)           81
812   Celluloid Closet, The (1995)           56
846     Looking for Richard (1996)           55
1064          Koyaanisqatsi (1983)           53

Top 5 movies for genre: Drama
                           title  num_ratings
257               Contact (1997)          509
99                  Fargo (1996)          508
285  English Patient, The (1996)          481
126        Godfather, The (1972)          413
55           Pulp Fiction (1994)          394

Top 5 movies for genre: Fantasy
                                 title  num_ratings
422  E.T. the Extra-Terrestrial (1982)          300
410        Nutty Professor, The (1996)          163
471                 Dragonheart (1996)          158
71                    Mask, The (1994)          129
754                     Jumanji (1995)           96

Top 5 movies for genre: Film-Noir
                                title  num_ratings
301          L.A. Confidential (1997)          297
88                Blade Runner (1982)          275
653                  Chinatown (1974)          147
483        Maltese Falcon, The (1941)          138
656  Manchurian Candidate, The (1962)          131

Top 5 movies for genre: Horror
                   title  num_ratings
287        Scream (1996)          478
182         Alien (1979)          291
233          Jaws (1975)          280
184        Psycho (1960)          239
199  Shining, The (1980)          206

Top 5 movies for genre: Musical
                          title  num_ratings
288                Evita (1996)          259
185  Blues Brothers, The (1980)          251
131    Wizard of Oz, The (1939)          246
142  Sound of Music, The (1965)          222
70        Lion King, The (1994)          220

Top 5 movies for genre: Mystery
                            title  num_ratings
404    Mission: Impossible (1996)          344
301      L.A. Confidential (1997)          297
327      Conspiracy Theory (1997)          295
190                Amadeus (1984)          276
134  2001: A Space Odyssey (1968)          259

Top 5 movies for genre: Romance
                               title  num_ratings
49                  Star Wars (1977)          583
180        Return of the Jedi (1983)          507
285      English Patient, The (1996)          481
236             Jerry Maguire (1996)          384
171  Empire Strikes Back, The (1980)          367

Top 5 movies for genre: Sci-Fi
                             title  num_ratings
49                Star Wars (1977)          583
257                 Contact (1997)          509
180      Return of the Jedi (1983)          507
120  Independence Day (ID4) (1996)          429
6            Twelve Monkeys (1995)          392

Top 5 movies for genre: Thriller
                                title  num_ratings
99                       Fargo (1996)          508
287                     Scream (1996)          478
299              Air Force One (1997)          431
97   Silence of the Lambs, The (1991)          390
116                  Rock, The (1996)          378

Top 5 movies for genre: War
                               title  num_ratings
49                  Star Wars (1977)          583
180        Return of the Jedi (1983)          507
285      English Patient, The (1996)          481
120    Independence Day (ID4) (1996)          429
171  Empire Strikes Back, The (1980)          367

Top 5 movies for genre: Western
                                         title  num_ratings
96                   Dances with Wolves (1990)          256
434  Butch Cassidy and the Sundance Kid (1969)          216
202                          Unforgiven (1992)          182
176     Good, The Bad and The Ugly, The (1966)          137
72                             Maverick (1994)          128